### ISSUE TITLE
Add ability to set custom domains/subdomains

### ISSUE THREAD

**Issue by bravomartin** [designsystemsinternational/clis#1]
I'd love to have the ability to set a custom domain name for a distribution. either on config (first deploy) or as a subsequent step. 

- The root domain would have to be configured to work on Route53 (returning error if not)
- It would ideally be listed in `show outputs` and `open` along with s3 and cloudfront urls

not exactly sure how this would work in AWS/cloudformation or if it's even possible

**Comment by runemadsen** [comment]
This is done!
