### ISSUE TITLE
add simple auth

### ISSUE THREAD

**Issue by bravomartin** [designsystemsinternational/clis#6]
add the option to enable basic auth with password. 
using lambda@edge

https://gist.github.com/lmakarov/e5984ec16a76548ff2b278c06027f1a4

**Comment by runemadsen** [comment]
Checklist:

- [ ] Use [this code](https://gist.github.com/lmakarov/e5984ec16a76548ff2b278c06027f1a4)
- [ ] Make sure to restrict bucket access to only the cloudfront URL
