### ISSUE TITLE
Suggest next steps after each.

### ISSUE THREAD

**Issue by bravomartin** [designsystemsinternational/clis#8]
after `static init`, it would be nice to have a message like:

```
project initialized. create your first distribution with `static create <distribution>`
```

similarly, after `static create` we can show something like:

```
project distribution created. run your first deploy on this distribution with `static deploy <distribution name>`
```

What if one of the questions of `static create` is  "do you want to run deploy after distribution is ready?"

**Comment by runemadsen** [comment]
This is sorta done
